version: '3.1'

services:
  database:
    image: postgres:14
    container_name: scala-project
    environment:
      - POSTGRES_DB=fast_payments
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=myuser
    ports:
      - "5434:5432"